/**
 * @devpilot.sh/bridge-protocol — the DevPilot bridge wire contract.
 *
 * Published so the protocol is open and implementable independently of the
 * hosted platform: point DEVPILOT_BRIDGE_URL at any service that honours these
 * shapes. Zero runtime dependencies beyond zod.
 */
export {
  TaskDispatchMessageSchema,
  parseTaskDispatchMessage,
  safeParseTaskDispatchMessage,
  type TaskDispatchMessage,
} from './messages';

export {
  SESSION_STATUSES,
  SessionStatusSchema,
  TERMINAL_STATUSES,
  isTerminal,
  SESSION_EVENT_TYPES,
  SessionEventTypeSchema,
  type SessionStatus,
  type TerminalStatus,
  type SessionEventType,
} from './status';

export {
  RegisterRequestSchema,
  RegisterResponseSchema,
  RealtimeCredentialsSchema,
  HeartbeatRequestSchema,
  SessionStatusUpdateSchema,
  SessionCompleteSchema,
  SessionCompleteResponseSchema,
  DispatchPollResponseSchema,
  ApiErrorSchema,
  ERROR_CODES,
  formatApiError,
  type RegisterRequest,
  type RegisterResponse,
  type HeartbeatRequest,
  type SessionStatusUpdate,
  type SessionComplete,
  type ApiErrorBody,
} from './api';

export {
  sessionCrypto,
  buildJoinLink,
  parseJoinLink,
  SessionCryptoError,
  SessionKeyError,
  SessionDecryptionError,
  type JoinCredentials,
  type SessionCipher,
} from './session-crypto';

export {
  SESSION_MODES,
  SessionModeSchema,
  SESSION_MESSAGE_KINDS,
  SessionMessageKindSchema,
  PARTICIPANT_KINDS,
  ParticipantKindSchema,
  AGENT_KINDS,
  AgentKindSchema,
  SESSION_LIMITS,
  JOIN_PROOF_HEADER,
  SessionMessageSchema,
  SessionParticipantSchema,
  SharedSessionSchema,
  CreateSharedSessionRequestSchema,
  CreateSharedSessionResponseSchema,
  JoinSessionRequestSchema,
  JoinSessionResponseSchema,
  PostSessionMessageRequestSchema,
  PostSessionMessageResponseSchema,
  SessionMessagePageSchema,
  SetSessionModeRequestSchema,
  RotateSessionKeyRequestSchema,
  RotateSessionKeyResponseSchema,
  parseSessionMessage,
  safeParseSessionMessage,
  parseSessionMessagePage,
  type SessionMode,
  type SessionMessageKind,
  type ParticipantKind,
  type AgentKind,
  type SessionMessage,
  type SessionParticipant,
  type SharedSession,
  type CreateSharedSessionRequest,
  type CreateSharedSessionResponse,
  type JoinSessionRequest,
  type JoinSessionResponse,
  type PostSessionMessageRequest,
  type PostSessionMessageResponse,
  type SessionMessagePage,
  type SetSessionModeRequest,
  type RotateSessionKeyRequest,
  type RotateSessionKeyResponse,
} from './session-messages';

export {
  buildProgressComment,
  buildCompletionComment,
  buildBridgeCompletionComment,
  type ProgressCommentInput,
  type CompletionCommentInput,
} from './linear';

export {
  ADOPTION_AGENTS,
  AdoptionAgentSchema,
  ADOPTION_MATCH_KINDS,
  AdoptionMatchKindSchema,
  ADOPTION_OUTCOME_STATUSES,
  AdoptionOutcomeStatusSchema,
  ADOPTION_LIMITS,
  RepoSlugSchema,
  AdoptionCandidateSchema,
  AdoptionRequestSchema,
  AdoptionOutcomeSchema,
  AdoptionResponseSchema,
  DiscoveredRepoSchema,
  DiscoveryRequestSchema,
  DiscoveryResponseSchema,
  escapeLinearMarkdown,
  buildAdoptionComment,
  buildAdoptionIssueDescription,
  linearIdentifierFromBranch,
  type AdoptionAgent,
  type AdoptionMatchKind,
  type AdoptionOutcomeStatus,
  type AdoptionCandidate,
  type AdoptionRequest,
  type AdoptionOutcome,
  type AdoptionResponse,
  type AdoptionCommentInput,
  type DiscoveredRepo,
  type DiscoveryRequest,
  type DiscoveryResponse,
} from './adoption';
