export {
  SCORE_MODEL,
  SCORE_DIMENSIONS,
  SCORE_TOTAL,
  SCORE_MODEL_VERSION,
  scoreModelIsValid,
  clampDimension,
  totalFrom,
  type ScoreDimension,
  type ScoreDimensionKey,
} from './model';

export {
  RUNWAY_TARGET_HOURS,
  MIN_RUNWAY_SAMPLES,
  MIN_RUNWAY_COVERED_MINUTES,
  MIN_TASKS_FOR_ACCURACY,
  MIN_COMPLETIONS_FOR_TREND,
  DEFAULT_RECENT_FRACTION,
  MIN_TASKS_FOR_PARALLELIZATION,
  RUNWAY_SAMPLE_MAX_HOLD_MINUTES,
  WORKING_BREAK_MINUTES,
  computeRunwayHealth,
  computeFleetUtilization,
  computePlanAccuracy,
  computeCostEfficiency,
  computeVelocityTrend,
  computeParallelizationQuality,
  measurePlanParallelization,
  computeScore,
  type DimensionResult,
  type ScoreResult,
  type ScoreInput,
  type TimeWindow,
  type RunwaySample,
  type RunwayHealthInput,
  type SessionInterval,
  type FleetUtilizationInput,
  type EstimatedTask,
  type PlanAccuracyInput,
  type UsageEntry,
  type CostEfficiencyInput,
  type VelocityTrendInput,
  type ExecutedTask,
  type ExecutedPlan,
  type ParallelizationInput,
  type PlanParallelization,
} from './compute';

export {
  MIN_HISTORY_FOR_ESTIMATE,
  buildScoreInput,
  estimateTasks,
  executedPlans,
  type ScoreEvidence,
  type ScoreRunwayRow,
  type ScoreSessionRow,
  type ScoreTaskRow,
  type ScoreWindowOptions,
} from './evidence';
