/**
 * Generate src/version.ts from package.json.
 *
 * `VERSION` was hand-maintained and drifted: the constant said 0.1.1 while the
 * package published 0.2.0, so `devpilot --version` reported a release that had
 * not existed for two versions. Anyone debugging a stale global install was
 * being told the wrong thing by the one command whose entire job is to answer
 * that question.
 *
 * Runs before build, so the two cannot disagree.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const { version } = JSON.parse(readFileSync(join(here, '..', 'package.json'), 'utf8'));
const target = join(here, '..', 'src', 'version.ts');

const contents = `// GENERATED by scripts/sync-version.mjs from package.json. Do not edit.
export const VERSION = '${version}';
`;

if (readFileSync(target, 'utf8') !== contents) {
  writeFileSync(target, contents);
  console.log(`version.ts -> ${version}`);
}
